# -*- coding: utf-8 -*-
"""IDclouds

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLDS6wKkWeAr6W01lyClMwt483grCMRm
"""

import streamlit as st
import numpy as np
import pandas as pd
from PIL import Image
import tensorflow as tf

st.title("Prueba 01")